package com.uitestflow.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import com.uitestflow.model.TestCase;
import com.uitestflow.model.TestFlow;
import com.uitestflow.model.TestStep;
import com.uitestflow.util.FlowParser;
import com.uitestflow.util.TestCaseGenerator;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.yaml.snakeyaml.Yaml;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.*;

/**
 * 测试用例生成服务
 */
@Service
public class TestCaseService {

    private final FlowParser flowParser;
    private final TestCaseGenerator testCaseGenerator;
    private final FlowService flowService;

    @Value("${output.directory:../output}")
    private String outputDirectory;

    private final ObjectMapper objectMapper = new ObjectMapper();
    private final Yaml yaml = new Yaml();

    public TestCaseService(FlowParser flowParser, TestCaseGenerator testCaseGenerator, FlowService flowService) {
        this.flowParser = flowParser;
        this.testCaseGenerator = testCaseGenerator;
        this.flowService = flowService;
    }

    /**
     * 生成测试用例
     */
    public List<TestCase> generateTestCases(String flowId) throws IOException {
        // 加载流程
        TestFlow flow = flowService.getFlow(flowId);

        // 加载所有流程，以便子流程展开
        Map<String, TestFlow> allFlows = new HashMap<>();
        String flowDir = flowService.getFlowDirectory();
        File dir = new File(flowDir);
        if (dir.exists() && dir.isDirectory()) {
            File[] files = dir.listFiles();
            if (files != null) {
                for (File f : files) {
                    if (f.getName().endsWith(".json")) {
                        try {
                            TestFlow subFlow = flowParser.loadFlow(f.getAbsolutePath());
                            allFlows.put(subFlow.getId(), subFlow);
                        } catch (Exception e) {
                            // 忽略加载失败的文件
                        }
                    }
                }
            }
        }

        // 生成用例
        List<TestCase> testCases = testCaseGenerator.generateTestCases(flow, allFlows);

        // 保存到输出目录
        String outputPath = Paths.get(outputDirectory, "test-cases.json").toString();
        File outputDir = new File(outputDirectory);
        if (!outputDir.exists()) {
            outputDir.mkdirs();
        }

        String json = objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(testCases);
        Files.write(Paths.get(outputPath), json.getBytes());

        return testCases;
    }

    /**
     * 获取测试用例列表
     */
    public List<TestCase> getTestCases() throws IOException {
        String outputPath = Paths.get(outputDirectory, "test-cases.json").toString();
        File file = new File(outputPath);

        if (!file.exists()) {
            return Collections.emptyList();
        }

        String content = String.join("", Files.readAllLines(Paths.get(outputPath)));
        return Arrays.asList(objectMapper.readValue(content, TestCase[].class));
    }

    /**
     * 导出测试用例
     */
    public String exportTestCases(String flowId, String format) throws IOException {
        // 支持 JSON 和 YAML 格式
        String jsonPath = Paths.get(flowService.getFlowDirectory(), flowId + ".json").toString();
        String yamlPath = Paths.get(flowService.getFlowDirectory(), flowId + ".yaml").toString();

        String filePath;
        if (new File(jsonPath).exists()) {
            filePath = jsonPath;
        } else if (new File(yamlPath).exists()) {
            filePath = yamlPath;
        } else {
            throw new IOException("流程不存在");
        }

        // 加载流程
        TestFlow flow = flowParser.loadFlow(filePath);

        // 生成用例
        List<TestCase> testCases = testCaseGenerator.generateTestCases(flow, null);

        switch (format) {
            case "yaml":
                return yaml.dump(testCases);
            case "script":
                return generateMidsceneScripts(testCases);
            default:
                return objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(testCases);
        }
    }

    /**
     * 生成 Midscene.js 脚本
     */
    private String generateMidsceneScripts(List<TestCase> testCases) {
        StringBuilder sb = new StringBuilder();
        sb.append("// Generated by UI Test Flow\n");
        sb.append("const { ai, aiAssert, aiQuery } = require('@midscenejs/playwright');\n\n");

        for (TestCase tc : testCases) {
            sb.append("// ").append(tc.getId()).append(": ").append(tc.getName()).append("\n");
            sb.append("async function test").append(tc.getId().replace("TC-", "")).append("(page) {\n");

            if (tc.getSteps() != null) {
                for (TestStep step : tc.getSteps()) {
                    if ("action".equals(step.getType())) {
                        if (step.getMethod() != null) {
                            String method = step.getMethod().name().toLowerCase();
                            if ("input".equals(method)) {
                                sb.append("  await ai('在").append(step.getTarget()).append("输入 ").append(step.getValue()).append("');\n");
                            } else if ("click".equals(method)) {
                                sb.append("  await ai('点击").append(step.getTarget()).append("');\n");
                            } else if ("wait".equals(method)) {
                                sb.append("  await page.waitForTimeout(").append(step.getTimeout() != null ? step.getTimeout() : 1000).append(");\n");
                            } else {
                                sb.append("  await ai('").append(step.getMethod().name()).append(" ").append(step.getTarget()).append("');\n");
                            }
                        }
                    } else if ("assert".equals(step.getType())) {
                        sb.append("  await aiAssert('").append(step.getTarget()).append("显示").append(step.getExpected()).append("');\n");
                    }
                }
            }

            sb.append("}\n\n");
        }

        return sb.toString();
    }
}
